server:
  port: 30000


spring:
  application:
    name: gulimall-cart

  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

  redis:
    port: 6379
    host: 192.168.18.166

  session:
    store-type: redis

gulimall:
  thread:
    coreSize: 20
    maxSize: 200
    keepAliveTime: 10